### ISSUE TITLE
Accept extra JVM options

### ISSUE THREAD

**Issue by cemsbr** [dremio/containers#2]
How can I use the docker image adding an extra JVM option like `-Duser.timezone=UTC`?

**Comment by Nirmalyasen** [comment]
You can use existing image and try passing JVM options via DREMIO_JAVA_EXTRA_OPTS environment variable in docker. e.g.

docker run -e DREMIO_JAVA_EXTRA_OPTS="-Duser.timezone=UTC" dremio/dremio-oss

**Comment by cemsbr** [comment]
Thank you, it worked.
