### ISSUE TITLE
Cannot create LoadBalancer with ClientIP affinity in AWS

### ISSUE THREAD

**Issue by rothgar** [dremio/containers#6]
When trying to deploy dremio with the example charts on EKS I get the following error for the dremio-client service that tries to create a load balancer endpoint.

```
Warning  CreatingLoadBalancerFailed  1m (x7 over 6m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/dremio-client: unsupported load balancer affinity: ClientIP
```

I haven't yet figured out if that affinity is needed but I wanted to open an issue to track it.

**Comment by Nirmalyasen** [comment]
Yes, session affinity is required back to the same coordinator that the UI connected to. 

Yes, AWS does not support ClientIP for session affinity - https://github.com/kubernetes/kubernetes/issues/13892
One needs to work around using Ingress controller.

**Comment by rothgar** [comment]
Right, so should the example manifests here create an ingress rule instead of a service LB which doesn't work?

**Comment by Nirmalyasen** [comment]
These templates work great on K8S clusters in Azure, GCE as well as Kubernetes on Docker. Hence these were published as samples for people to build upon. 

In fact, you could comment out the LoadBalancer and then it will create a NodePort for the service. If the nodes are accessible for you, you can access them via the NodePort too,

**Comment by rothgar** [comment]
Thanks for the info. I checked to see if there was a way to detect if k8s was running in AWS or GKE/AKS but it doesn't look like it exposes that information. I'll go ahead and fork the base templates you provided and create my own for AWS.
